### ISSUE TITLE
TypeError - "listener" argument must be a function [events.js line239]

### ISSUE THREAD

**Issue by navyblueyes** [tsahilevi/webrtc-missing-codelab#3]
Getting the following error after starting with "npm start"
![missing-codelab-listener-error](https://user-images.githubusercontent.com/28884422/94877895-ae963700-0410-11eb-865c-43895ee5499a.png)

```
> minimal-signaling-server@1.0.0 start /mnt/c/Users/Micha/.LocalCode/webrtc-missing-codelab
> node server.js

events.js:239
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:269:10)
    at Object.Server (_http_server.js:265:41)
    at Object.<anonymous> (/mnt/c/Users/Micha/.LocalCode/webrtc-missing-codelab/server.js:12:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! minimal-signaling-server@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minimal-signaling-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-02T00_58_02_357Z-debug.log
```

https://imgbox.com/gfXUNQ4Y#

**Comment by fippo** [comment]
What nodejs version are you using?

**Comment by navyblueyes** [comment]
I am using 6.14.5 npm

**Comment by fippo** [comment]
and what node version (`node -v`)? I can tentatively fix it as suggested in the comment above but would like to understand where it fails)

**Comment by fippo** [comment]
closing, assuming node6 is outdated
